version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_DATABASE: phonebook_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: Clarusway_1
        volumes:
            - db-data:/var/lib/mysql
        configs:
            - source: table #name is up to you
              target: /docker-entrypoint-initdb.d/init.sql # docker documentation says it can run init.sql file if you put it under /docker-entrypoint-initdb.d
        networks:
            - clarusnet
    app-server:
        env_file: .env # template user datada .env diye bir file olusturcaz ve icine {ECR_REGISTRY}/${APP_REPO_NAME} olusucak ismi gondercez ve compose daoradan cekecek
        image: "${ECR_REPO}:latest" #  {ECR_REGISTRY}/${APP_REPO_NAME}:latest olarak da yazabilirdin mesela
        deploy:
            mode: global # her nodeda 1 tane ac demek
            update_config: # containerlara guncelleme yaptigimda 2 ser 2 ser acip kapat
                parallelism: 2
                delay: 5s
                order: start-first
        ports:
            - "80:80"
        networks:
            - clarusnet
networks:
    clarusnet:
        driver: overlay

volumes: # here we are using named volume
    db-data:

configs:
    table: #name is up to you
        file: ./init.sql